"""Protocol interfaces for dependency injection."""

from __future__ import annotations
from typing import Protocol, Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    pass


class BrokerProtocol(Protocol):
    def on_candle(
        self, candle: Any, order: Optional[Dict[str, Any]], tick: Optional[Any] = None
    ) -> Dict[str, Any]: ...
    def save_state(self) -> None: ...
    def shutdown(self) -> None: ...
    def close_all(self, current_price: float) -> List[Dict[str, Any]]: ...
    def get_unrealized_pnl(self, current_price: float) -> float: ...
    @property
    def pos(self) -> Optional[Any]: ...
    @property
    def current_equity(self) -> float: ...
    @property
    def is_inverse(self) -> bool: ...


class ProviderProtocol(Protocol):
    def load_rest_candles(
        self, symbol: str, interval: str, limit: int
    ) -> List[Any]: ...
    def get_instrument_info(self, symbol: str) -> Dict[str, Any]: ...


class StateManagerProtocol(Protocol):
    def save(self) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
